### ISSUE TITLE
Allow not collecting billing information

### ISSUE THREAD

**Issue by thenchev** [btcpayserver/commerce_btcpay#18]
Support the new feature: <a href="https://www.drupal.org/node/3050426">requires_billing_information</a>

Here is the parent issue: https://www.drupal.org/project/commerce/issues/3077499

**Comment by ndeet** [comment]
Hi @thenchev thank you for pointing this out and your meta-issue and d.o. @iBobik was so kind to fix this with https://github.com/btcpayserver/commerce_btcpay/pull/16 way back in June which I merged now. And released a new version 8.x-1.0-alpha3
